id: task_rcjf
type: task
title: "Практика: РКЗФ"
time_estimate_min: 5
illustration: magic
mascot_quip: "Давай, покомандуй мной! Но по формуле. 😎"
task_prompt: "Напишите промпт по формуле РКЗФ."
evaluation_criteria: "Промпт должен содержать Роль (спичрайтер), Контекст (день города, губернатор), Задачу (написать речь), Формат (вдохновляюще, кратко)."
next_step: step-4-theory

