id: start
type: intro
title: "Введение: ИИ на госслужбе"
time_estimate_min: 5
illustration: rocket
mascot_quip: "Обещаю не захватывать мир... пока ты не научишься писать промпты! 😉"
next_step: step-1-theory

