id: theory_prompting
type: theory
title: "Формула РКЗФ: Основа промптинга"
time_estimate_min: 7
illustration: memo
mascot_quip: "Без внятного ТЗ — результат ХЗ. Это правило работает и с людьми, и со мной."
next_step: step-3-task

