id: theory_llm
type: theory
title: "Модуль 1. Как думает машина?"
time_estimate_min: 5
illustration: brain
mascot_quip: "У меня нет мозга, только математика. Но иногда я очень убедительно вру! 🦜"
next_step: step-2-theory

