id: theory_safety
type: theory
title: "Модуль 3. Красные линии"
time_estimate_min: 5
illustration: shield
mascot_quip: "Твои секреты умрут со мной... ну, или останутся на серверах навсегда. Лучше не рискуй! 🤐"
next_step: step-9-task

